name: Python package

on:
  push:
    branches: [ main, master ]  # Trigger on push to main branches
  pull_request:
    branches: [ main, master ]  # Trigger on PRs to main branches

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Continue with other versions even if one fails
      matrix:
        python-version: ["3.8", "3.9", "3.10"]  # Updated Python versions

    steps:
    - uses: actions/checkout@v3  # Updated to v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -e .
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest --cov=kaggl_air tests/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true